# Generated by Django 6.0.5 on 2026-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50, unique=True)),
                ('machine_id', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_by', models.CharField(default='AI Chatbot triage', max_length=100)),
                ('issue_description', models.TextField()),
                ('severity', models.CharField(default='critical', max_length=50)),
                ('status', models.CharField(default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
