# Generated by Django 6.0.5 on 2026-05-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('sender_role', models.CharField(default='manager', max_length=50)),
                ('recipient', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('priority', models.CharField(default='normal', max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('folder', models.CharField(default='inbox', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
