# Generated by Django 5.2 on 2026-05-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_cm', models.FloatField(help_text='Distance measured by HC-SR04 in centimetres')),
                ('is_flood_alert', models.BooleanField(default=False, help_text='True when distance < FLOOD_THRESHOLD_CM')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
