# Generated by Django 6.0.5 on 2026-05-22 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerId', models.CharField(max_length=50)),
                ('workerName', models.CharField(max_length=100)),
                ('clockIn', models.DateTimeField(default=django.utils.timezone.now)),
                ('clockOut', models.DateTimeField(blank=True, null=True)),
                ('locationLat', models.FloatField()),
                ('locationLng', models.FloatField()),
                ('isValid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('workerId', models.CharField(default='T-492', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('locationZone', models.CharField(max_length=50)),
                ('healthScore', models.IntegerField(default=100)),
                ('status', models.CharField(default='online', max_length=20)),
                ('uptimeHours', models.IntegerField(default=0)),
                ('lastServiceDate', models.CharField(max_length=50)),
                ('temp', models.FloatField(default=0.0)),
                ('vibration', models.FloatField(default=0.0)),
                ('pressure', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('machineId', models.CharField(max_length=50)),
                ('machineName', models.CharField(max_length=100)),
                ('reportedBy', models.CharField(max_length=100)),
                ('assignedTo', models.CharField(blank=True, max_length=100, null=True)),
                ('issueDescription', models.TextField()),
                ('aiAssessment', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(default='complex', max_length=20)),
                ('status', models.CharField(default='open', max_length=20)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('checklist', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('workerId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('lastUpdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
                ('image', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
        ),
    ]
