# Generated by Django 6.0.5 on 2026-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolvedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
