# Generated by Django 6.0.5 on 2026-05-22 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket_resolvedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(default='mobile-cam-01', max_length=100)),
                ('image', models.TextField()),
                ('activityScore', models.FloatField(default=0.0)),
                ('workerCount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
