#!/usr/bin/env node
/**
 * Inlines leaflet.js + leaflet.css from node_modules into a generated TS file
 * so the WebView never depends on a CDN. This makes the map render on first
 * paint even with no internet, fixing the release-build crash where the
 * unpkg.com fetch would hang or fail and bring the WebView down.
 *
 * Re-run after upgrading leaflet:  node scripts/inline-leaflet.js
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const leafletJsPath = path.join(root, 'node_modules', 'leaflet', 'dist', 'leaflet.js');
const leafletCssPath = path.join(root, 'node_modules', 'leaflet', 'dist', 'leaflet.css');
const outPath = path.join(root, 'components', 'leaflet-inline.ts');

if (!fs.existsSync(leafletJsPath)) {
  console.error('[inline-leaflet] missing leaflet.js — run `npm install leaflet@1.9.4` first');
  process.exit(1);
}
if (!fs.existsSync(leafletCssPath)) {
  console.error('[inline-leaflet] missing leaflet.css');
  process.exit(1);
}

const leafletJs = fs.readFileSync(leafletJsPath, 'utf8');
const leafletCss = fs.readFileSync(leafletCssPath, 'utf8');

// JSON.stringify gives us a perfectly-escaped JS string literal that is safe
// to drop into a TypeScript source file — including all backticks, backslashes,
// and unicode characters in the Leaflet bundle.
const jsLiteral = JSON.stringify(leafletJs);
const cssLiteral = JSON.stringify(leafletCss);

const banner = `// AUTO-GENERATED by scripts/inline-leaflet.js — do not edit by hand.
// Source: leaflet@1.9.4 from node_modules/leaflet/dist/{leaflet.js,leaflet.css}
// Run \`node scripts/inline-leaflet.js\` to regenerate.
`;

const body = `${banner}
export const LEAFLET_JS: string = ${jsLiteral};
export const LEAFLET_CSS: string = ${cssLiteral};
`;

fs.writeFileSync(outPath, body, 'utf8');
console.log(
  `[inline-leaflet] wrote ${outPath} (${(body.length / 1024).toFixed(1)} KB)`,
);
