# Generated by Django 5.2 on 2026-05-23 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrainReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('drain_location', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=15.5938)),
                ('lng', models.FloatField(default=73.8035)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('clear', 'Clear'), ('debris', 'Debris Detected'), ('adopted', 'Adopted')], default='adopted', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drain_reports/')),
                ('notes', models.TextField(blank=True)),
                ('points_awarded', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=15.5938)),
                ('lng', models.FloatField(default=73.8035)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='flood_reports/')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('water_depth_estimate', models.FloatField(default=0.0, help_text='Estimated water depth in cm')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated Flood'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('validation_score', models.FloatField(default=0.0, help_text='Gemini confidence 0-1')),
                ('gemini_notes', models.TextField(blank=True, help_text='Gemini Vision analysis notes')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('badge_level', models.CharField(choices=[('rookie', 'Rookie'), ('reporter', 'Reporter'), ('guardian', 'Flood Guardian')], default='rookie', max_length=20)),
                ('total_reports', models.IntegerField(default=0)),
                ('accurate_reports', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='ReportVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(help_text='Anonymous voter fingerprint (UUID from frontend)', max_length=100)),
                ('vote', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reports.floodreport')),
            ],
            options={
                'unique_together': {('report', 'voter_id')},
            },
        ),
    ]
