"use client";

import React, { useEffect, useState, useCallback } from "react";
import { API_URL, WS_URL } from "@/lib/api";

interface ThreatEntry {
  id: string;
  bin: string;
  issuer: string;
  type: string;
  source: string;
  risk: string;
  created_at: string;
}

const externalFeeds = [
  { name: "CERT-In National Feed", status: "SYNCED", latency: "14ms", lastUpdate: "Live" },
  { name: "Interpol Red Notices", status: "SYNCED", latency: "45ms", lastUpdate: "12 mins ago" },
  { name: "Dark Web Scraper v4", status: "ACTIVE", latency: "110ms", lastUpdate: "Live" },
  { name: "Global BIN Blacklist", status: "SYNCED", latency: "22ms", lastUpdate: "2 hours ago" },
];

const STATIC_THREATS: ThreatEntry[] = [
  { id: "T1", bin: "4214 56XX XXXX XXXX", issuer: "HDFC Bank", type: "VISA Signature", source: "Genesis Market", risk: "Critical", created_at: new Date(Date.now() - 4 * 60000).toISOString() },
  { id: "T2", bin: "5241 12XX XXXX XXXX", issuer: "ICICI Bank", type: "Mastercard World", source: "Joker's Stash Reborn", risk: "Critical", created_at: new Date(Date.now() - 28 * 60000).toISOString() },
  { id: "T3", bin: "6071 88XX XXXX XXXX", issuer: "RuPay", type: "Platinum", source: "Telegram Leak Channel", risk: "High", created_at: new Date(Date.now() - 3600000).toISOString() },
  { id: "T4", bin: "4512 09XX XXXX XXXX", issuer: "Axis Bank", type: "VISA Platinum", source: "Dark Web Forum", risk: "High", created_at: new Date(Date.now() - 3 * 3600000).toISOString() },
  { id: "T5", bin: "4147 20XX XXXX XXXX", issuer: "SBI", type: "VISA Classic", source: "Genesis Market", risk: "Medium", created_at: new Date(Date.now() - 5 * 3600000).toISOString() },
];

function timeAgo(iso: string): string {
  const diff = (Date.now() - new Date(iso).getTime()) / 1000;
  if (diff < 60) return `${Math.floor(diff)}s ago`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

export default function ThreatIntelPage() {
  const [threats, setThreats] = useState<ThreatEntry[]>(STATIC_THREATS);
  const [backendOnline, setBackendOnline] = useState(false);
  const [pulse, setPulse] = useState(false);

  const fetchThreats = useCallback(async () => {
    try {
      const res = await fetch(`${API_URL}/api/v1/threats`);
      if (!res.ok) throw new Error();
      const data: ThreatEntry[] = await res.json();
      if (data.length > 0) {
        setThreats(data);
        setBackendOnline(true);
      }
    } catch {
      setBackendOnline(false);
    }
  }, []);

  useEffect(() => {
    fetchThreats();
    const interval = setInterval(fetchThreats, 30000); // Poll every 30s for new dark web entries
    return () => clearInterval(interval);
  }, [fetchThreats]);

  useEffect(() => {
    const interval = setInterval(() => setPulse(p => !p), 2000);
    return () => clearInterval(interval);
  }, []);

  const criticalCount = threats.filter(t => t.risk === 'Critical').length;

  return (
    <div className="flex flex-col h-full space-y-4 overflow-hidden">

      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-xl font-black tracking-tight text-white">Global Threat Intelligence</h2>
          <p className="text-xs font-mono text-slate-500 mt-1">Dark web monitoring, BIN compromise feeds, and macro threat tracking.</p>
        </div>
        <div className="flex items-center gap-2 text-[10px] font-mono">
          <span className={`w-2 h-2 rounded-full ${backendOnline ? 'bg-green-500 animate-pulse' : 'bg-slate-600'}`}></span>
          <span className={backendOnline ? 'text-green-500' : 'text-slate-500'}>
            {backendOnline ? 'LIVE — New BINs generated by backend scraper' : 'OFFLINE — Static data'}
          </span>
        </div>
      </div>

      <div className="flex gap-4 flex-1 min-h-0">

        {/* Left: DEFCON + Feed Health */}
        <div className="w-80 flex flex-col gap-4 flex-shrink-0">

          {/* DEFCON Gauge */}
          <div className="bg-[var(--bg-card)] border border-[var(--border-color)] p-6 flex flex-col items-center relative overflow-hidden">
            <div className="absolute top-3 left-3 text-[9px] font-mono text-slate-500 uppercase tracking-widest">Macro Threat Level</div>

            <div className="relative w-40 h-40 flex items-center justify-center mt-4">
              <div className={`absolute inset-0 rounded-full border border-[var(--risk-amber)]/20 transition-all duration-1000 ${pulse ? 'scale-110 opacity-0' : 'scale-100 opacity-100'}`}></div>
              <div className={`absolute inset-3 rounded-full border border-[var(--risk-amber)]/30 transition-all duration-1000 delay-150 ${pulse ? 'scale-105 opacity-0' : 'scale-100 opacity-100'}`}></div>
              <div className="w-28 h-28 rounded-full bg-[#0a0a0a] border-2 border-[var(--risk-amber)] flex flex-col items-center justify-center">
                <span className="text-[9px] font-mono text-[var(--risk-amber)] tracking-widest">DEFCON</span>
                <span className="text-5xl font-black text-white mt-1">3</span>
              </div>
            </div>

            <div className="mt-4 text-center">
              <h4 className="text-sm font-bold text-[var(--risk-amber)] uppercase tracking-wider">Elevated Risk</h4>
              <p className="text-[10px] font-mono text-slate-500 mt-1">Coordinated phishing campaign detected targeting tier-1 banks in South Asia.</p>
            </div>
          </div>

          {/* Feed Health */}
          <div className="flex-1 bg-[var(--bg-card)] border border-[var(--border-color)] flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-800 bg-[#0a0a0a]">
              <h3 className="text-[10px] font-mono tracking-widest text-slate-400 uppercase">Integration Health</h3>
            </div>
            <div className="flex-1 p-4 space-y-4 overflow-y-auto scrollbar-hide">
              {externalFeeds.map((feed, i) => (
                <div key={i} className="flex justify-between items-center border-b border-slate-800/40 pb-3 last:border-0 last:pb-0">
                  <div>
                    <p className="text-xs font-bold text-slate-200">{feed.name}</p>
                    <p className="text-[9px] font-mono text-slate-600 mt-1">Lat: {feed.latency} · {feed.lastUpdate}</p>
                  </div>
                  <span className="text-[9px] font-mono px-2 py-0.5 bg-green-500/10 text-green-400 border border-green-500/20">
                    {feed.status}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right: Dark Web BIN Dump Feed */}
        <div className="flex-1 bg-[var(--bg-card)] border border-[var(--border-color)] flex flex-col overflow-hidden">
          <div className="p-4 border-b border-slate-800 bg-[#0a0a0a] flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-1 h-5 bg-[var(--risk-red)]"></div>
              <div>
                <h3 className="text-xs font-mono font-bold text-white uppercase tracking-wider">Compromised BIN Monitor</h3>
                <p className="text-[9px] font-mono text-slate-500">Live scraping of dark web marketplaces for Bank Identification Numbers</p>
              </div>
            </div>
            {criticalCount > 0 && (
              <span className="text-[10px] font-mono bg-[var(--risk-red)] text-white px-3 py-1 font-bold">
                {criticalCount} CRITICAL
              </span>
            )}
          </div>

          <div className="flex-1 overflow-y-auto scrollbar-hide divide-y divide-slate-800/50">
            {threats.map((t) => (
              <div key={t.id} className="p-4 hover:bg-white/[0.02] transition-colors">
                <div className="flex justify-between items-start mb-3">
                  <div className="flex items-center gap-3">
                    <div className="bg-[#0a0a0a] border border-slate-700 px-3 py-1.5 font-mono text-sm text-white tracking-widest">
                      {t.bin}
                    </div>
                    <span className={`text-[9px] font-mono px-2 py-0.5 border uppercase tracking-wider ${
                      t.risk === 'Critical' ? 'bg-[var(--risk-red)]/10 text-[var(--risk-red)] border-[var(--risk-red)]/30' :
                      t.risk === 'High' ? 'bg-[var(--risk-amber)]/10 text-[var(--risk-amber)] border-[var(--risk-amber)]/30' :
                      'bg-slate-800 text-slate-400 border-slate-700'
                    }`}>{t.risk} EXPOSURE</span>
                  </div>
                  <span className="text-[9px] font-mono text-slate-500 flex-shrink-0">{timeAgo(t.created_at)}</span>
                </div>

                <div className="grid grid-cols-3 gap-4 mb-3">
                  <div>
                    <p className="text-[9px] font-mono text-slate-600 uppercase tracking-widest">Issuer</p>
                    <p className="text-xs text-slate-300 mt-1">{t.issuer}</p>
                  </div>
                  <div>
                    <p className="text-[9px] font-mono text-slate-600 uppercase tracking-widest">Card Type</p>
                    <p className="text-xs text-slate-300 mt-1">{t.type}</p>
                  </div>
                  <div>
                    <p className="text-[9px] font-mono text-slate-600 uppercase tracking-widest">Intel Source</p>
                    <p className="text-xs text-[var(--accent-copper)] font-mono mt-1">{t.source}</p>
                  </div>
                </div>

                <div className="flex justify-end gap-2">
                  <button className="text-[9px] font-mono text-slate-500 hover:text-white px-3 py-1.5 border border-slate-700 hover:border-slate-500 transition-colors">IGNORE</button>
                  <button className="text-[9px] font-mono text-white bg-[var(--accent-copper)] hover:bg-[#c27c3d] px-3 py-1.5 transition-colors font-bold">AUTO-BLOCK BIN</button>
                </div>
              </div>
            ))}

            {threats.length === 0 && (
              <div className="p-20 text-center text-slate-600 font-mono text-xs">No threats found yet. Backend scraper is running…</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
