import { motion } from 'framer-motion';
import { ScanSearch, Mic, FileSearch, Database, BarChart2, ArrowRight } from 'lucide-react';

const FEATURES = [
  {
    icon: ScanSearch,
    title: 'Face-Swap & GAN Detection',
    desc: 'Detects blending seams, pixel boundary artifacts, and GAN discriminator signatures that reveal face-swaps created with DeepFaceLab, FaceSwap, and Stable Diffusion.',
    color: '#ff2d55',
    bg: 'rgba(255,45,85,0.07)',
    border: 'rgba(255,45,85,0.2)',
    tag: 'Images & Video',
  },
  {
    icon: Mic,
    title: 'Voice Cloning Detection',
    desc: 'Analyses audio waveform envelopes, formant patterns, and lip-sync correlation scores to identify cloned voices generated by ElevenLabs, Resemble, or similar tools.',
    color: '#a855f7',
    bg: 'rgba(168,85,247,0.07)',
    border: 'rgba(168,85,247,0.2)',
    tag: 'Video & Audio',
  },
  {
    icon: FileSearch,
    title: 'EXIF Metadata Forensics',
    desc: 'Parses all IFD blocks, XMP sidecars, and container headers to detect metadata scrubbing, fabricated device fingerprints, and impossible timestamp signatures.',
    color: '#00d4ff',
    bg: 'rgba(0,212,255,0.07)',
    border: 'rgba(0,212,255,0.2)',
    tag: 'All Media Types',
  },
  {
    icon: BarChart2,
    title: 'Temporal Consistency Scan',
    desc: 'Frame-by-frame lighting vector analysis, blink frequency monitoring, and micro-expression tracking to catch face-reenactment models like First Order Motion.',
    color: '#00ff88',
    bg: 'rgba(0,255,136,0.06)',
    border: 'rgba(0,255,136,0.2)',
    tag: 'Video Only',
  },
  {
    icon: Database,
    title: 'Harassment Database Lookup',
    desc: 'Cross-references perceptual hashes against NCII, StopNCII, and partner law-enforcement watchlists to identify content from known harassment campaigns.',
    color: '#ffb800',
    bg: 'rgba(255,184,0,0.07)',
    border: 'rgba(255,184,0,0.2)',
    tag: 'All Media Types',
  },
];

const HOW_IT_WORKS = [
  { step: '01', title: 'Upload Media', desc: 'Drag & drop or select any image or video file. All files are processed in-memory and never stored.' },
  { step: '02', title: 'Pipeline Analysis', desc: 'Five AI models run in sequence — EXIF, GAN detection, temporal scan, database lookup, and final scoring.' },
  { step: '03', title: 'Get Forensic Report', desc: 'Receive a full verdict with detailed technical breakdown and a downloadable PDF for platform takedown requests.' },
];

export default function FeatureSection() {
  return (
    <div className="space-y-20">
      {/* ── Capability cards ───────────────────────────────────────────────── */}
      <section>
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.5 }}
          className="flex items-center gap-4 mb-8"
        >
          <div className="h-px flex-1 bg-gradient-to-r from-transparent via-slate-700 to-transparent" />
          <div className="flex items-center gap-2 px-4 py-1.5 rounded-full border border-slate-700 bg-slate-900/60">
            <span className="w-1.5 h-1.5 rounded-full bg-cyan-400" />
            <span className="text-slate-400 text-xs font-mono font-semibold tracking-widest">DETECTION CAPABILITIES</span>
          </div>
          <div className="h-px flex-1 bg-gradient-to-r from-transparent via-slate-700 to-transparent" />
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {FEATURES.map((f, i) => {
            const Icon = f.icon;
            return (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.1 }}
                transition={{ duration: 0.45, delay: i * 0.07 }}
                whileHover={{ y: -3, transition: { duration: 0.2 } }}
                className="rounded-2xl border p-6 group cursor-default"
                style={{ background: f.bg, borderColor: f.border }}
              >
                {/* Icon row */}
                <div className="flex items-start justify-between mb-4">
                  <div className="w-11 h-11 rounded-xl flex items-center justify-center"
                    style={{ background: `${f.color}18`, border: `1px solid ${f.color}30` }}>
                    <Icon className="w-5 h-5" style={{ color: f.color }} />
                  </div>
                  <span className="text-xs px-2.5 py-1 rounded-lg font-mono font-semibold"
                    style={{ color: f.color, background: `${f.color}12`, border: `1px solid ${f.color}25` }}>
                    {f.tag}
                  </span>
                </div>

                {/* Title */}
                <h3 className="text-white font-bold text-base mb-2 group-hover:text-cyan-50 transition-colors">
                  {f.title}
                </h3>

                {/* Description */}
                <p className="text-slate-500 text-sm leading-relaxed">
                  {f.desc}
                </p>

                {/* Hover accent bar */}
                <div className="mt-5 h-0.5 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                  style={{ background: `linear-gradient(90deg, ${f.color}, transparent)` }} />
              </motion.div>
            );
          })}

          {/* CTA card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.1 }}
            transition={{ duration: 0.45, delay: FEATURES.length * 0.07 }}
            className="rounded-2xl border border-dashed border-slate-700/60 p-6 flex flex-col items-center justify-center text-center gap-4 bg-slate-900/20"
          >
            <div className="w-12 h-12 rounded-xl bg-slate-800 border border-slate-700 flex items-center justify-center">
              <ArrowRight className="w-5 h-5 text-slate-400" />
            </div>
            <div>
              <p className="text-slate-300 font-semibold text-sm">More Models Coming</p>
              <p className="text-slate-600 text-xs mt-1">StyleGAN3 detection, lip-sync scoring, and content provenance tracking</p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── How it works ───────────────────────────────────────────────────── */}
      <section>
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.5 }}
          className="flex items-center gap-4 mb-8"
        >
          <div className="h-px flex-1 bg-gradient-to-r from-transparent via-slate-700 to-transparent" />
          <div className="flex items-center gap-2 px-4 py-1.5 rounded-full border border-slate-700 bg-slate-900/60">
            <span className="w-1.5 h-1.5 rounded-full bg-purple-400" />
            <span className="text-slate-400 text-xs font-mono font-semibold tracking-widest">HOW IT WORKS</span>
          </div>
          <div className="h-px flex-1 bg-gradient-to-r from-transparent via-slate-700 to-transparent" />
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 relative">
          {/* Connector line (desktop) */}
          <div className="hidden md:block absolute top-9 left-[16.67%] right-[16.67%] h-px bg-gradient-to-r from-cyan-500/20 via-purple-500/20 to-cyan-500/20" />

          {HOW_IT_WORKS.map((step, i) => (
            <motion.div
              key={step.step}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
              className="relative text-center p-6 rounded-2xl bg-slate-900/40 border border-slate-800"
            >
              {/* Step number */}
              <div className="relative z-10 w-14 h-14 rounded-2xl mx-auto mb-4 flex items-center justify-center"
                style={{
                  background: 'linear-gradient(135deg, rgba(0,212,255,0.1), rgba(168,85,247,0.1))',
                  border: '1px solid rgba(0,212,255,0.2)',
                }}>
                <span className="text-xl font-black font-mono text-cyan-400">{step.step}</span>
              </div>
              <h3 className="text-white font-bold text-base mb-2">{step.title}</h3>
              <p className="text-slate-500 text-sm leading-relaxed">{step.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  );
}
