import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, Target, AlertTriangle, CheckCircle2, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function MiniGame() {
  const navigate = useNavigate();
  const [gameState, setGameState] = useState('playing'); // playing, revealed
  const [selectedId, setSelectedId] = useState(null);

  const images = [
    {
      id: 1,
      url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
      isFake: false,
    },
    {
      id: 2,
      url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
      isFake: true,
    }
  ];

  const handleGuess = (id) => {
    if (gameState === 'revealed') return;
    setSelectedId(id);
    setGameState('revealed');
  };

  return (
    <div className="relative z-10 w-full px-8 pb-24">
      <div className="max-w-5xl mx-auto rounded-3xl border border-slate-700/60 overflow-hidden bg-slate-900/50 p-8 lg:p-12"
           style={{ boxShadow: '0 0 40px rgba(0,0,0,0.5)' }}>
        
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-purple-500/30 bg-purple-500/10 mb-4">
            <Target className="w-4 h-4 text-purple-400" />
            <span className="text-purple-400 text-xs font-mono font-bold tracking-widest">INTERACTIVE CHALLENGE</span>
          </div>
          <h2 className="text-white text-3xl md:text-4xl font-black mb-4">
            Can you spot the <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-400 to-purple-500">Deepfake?</span>
          </h2>
          <p className="text-slate-400 text-base max-w-2xl mx-auto">
            One of these images is a real human. The other was generated by a neural network. Click on the image you think is FAKE.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10 relative">
          {images.map((img) => {
            const isSelected = selectedId === img.id;
            const showReal = gameState === 'revealed' && !img.isFake;
            const showFake = gameState === 'revealed' && img.isFake;
            const borderClass = gameState === 'revealed'
              ? (img.isFake ? 'border-red-500 shadow-[0_0_30px_rgba(255,45,85,0.3)]' : 'border-green-500 shadow-[0_0_30px_rgba(0,255,136,0.2)]')
              : 'border-slate-700 hover:border-purple-500 hover:shadow-[0_0_20px_rgba(168,85,247,0.3)] cursor-pointer';

            return (
              <motion.div
                key={img.id}
                whileHover={gameState === 'playing' ? { scale: 1.02 } : {}}
                whileTap={gameState === 'playing' ? { scale: 0.98 } : {}}
                onClick={() => handleGuess(img.id)}
                className={`relative aspect-[4/5] rounded-2xl overflow-hidden border-2 transition-all duration-500 ${borderClass}`}
              >
                <img src={img.url} alt="Challenge option" className="absolute inset-0 w-full h-full object-cover" />
                
                {/* Overlay for revealed state */}
                <AnimatePresence>
                  {gameState === 'revealed' && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center p-6 text-center"
                    >
                      {showFake ? (
                        <>
                          <div className="w-16 h-16 rounded-full bg-red-500/20 border border-red-500/40 flex items-center justify-center mb-4 backdrop-blur-sm">
                            <AlertTriangle className="w-8 h-8 text-red-500" />
                          </div>
                          <h3 className="text-white text-2xl font-black mb-2">AI Generated</h3>
                          <div className="bg-red-500/20 border border-red-500/40 px-3 py-1 rounded text-red-400 text-xs font-mono font-bold">
                            98.4% GAN ARTIFACTS
                          </div>
                          {isSelected && <p className="text-white font-bold mt-4 bg-black/50 px-3 py-1 rounded-full text-sm">You got it right! 🎉</p>}
                        </>
                      ) : (
                        <>
                          <div className="w-16 h-16 rounded-full bg-green-500/20 border border-green-500/40 flex items-center justify-center mb-4 backdrop-blur-sm">
                            <CheckCircle2 className="w-8 h-8 text-green-400" />
                          </div>
                          <h3 className="text-white text-2xl font-black mb-2">Real Human</h3>
                          <div className="bg-green-500/20 border border-green-500/40 px-3 py-1 rounded text-green-400 text-xs font-mono font-bold">
                            VERIFIED AUTHENTIC
                          </div>
                          {isSelected && <p className="text-red-400 font-bold mt-4 bg-black/50 px-3 py-1 rounded-full text-sm">You guessed wrong! ❌</p>}
                        </>
                      )}
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>

        {/* Revealed Footer CTA */}
        <AnimatePresence>
          {gameState === 'revealed' && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="text-center bg-slate-950/50 border border-slate-800 rounded-2xl p-8"
            >
              <h4 className="text-white text-xl font-bold mb-3">AI is getting too good for the human eye.</h4>
              <p className="text-slate-400 text-sm mb-6 max-w-xl mx-auto leading-relaxed">
                Most humans fail this test. While the naked eye might be fooled by modern synthetic media, Aegis analyzes sub-pixel inconsistencies, lighting vectors, and EXIF metadata to detect fakes in milliseconds.
              </p>
              <button
                onClick={() => navigate('/portal')}
                className="inline-flex items-center gap-2 px-8 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-500 hover:from-cyan-400 hover:to-purple-400 text-white font-bold transition-all shadow-[0_0_20px_rgba(0,212,255,0.3)]"
              >
                <Shield className="w-5 h-5" />
                Try the Aegis Portal
                <ArrowRight className="w-5 h-5" />
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
